Traceback (most recent call last):
  File "format.py", line 373, in <module>
    raise Exception('this is an error message.')
Exception: this is an error message.
